#!/bin/bash

mkdir -p appdata/space-engineers-alice/bins/SpaceEngineersDedicated
mkdir -p appdata/space-engineers-alice/bins/steamcmd
mkdir -p appdata/space-engineers-alice/config/World
mkdir -p appdata/space-engineers-alice/config/Plugins
if [ ! -f ./appdata/space-engineers-alice/config/World/Sandbox.sbc ]; then
    echo "World not found, initalizing empty star system..."
    unzip -n star-system-alice.zip -d ./appdata/space-engineers-alice/config
fi

mkdir -p appdata/space-engineers-bob/bins/SpaceEngineersDedicated
mkdir -p appdata/space-engineers-bob/bins/steamcmd
mkdir -p appdata/space-engineers-bob/config/World
mkdir -p appdata/space-engineers-bob/config/Plugins
if [ ! -f ./appdata/space-engineers-bob/config/World/Sandbox.sbc ]; then
    echo "World not found, initalizing empty star system..."
    unzip -n star-system-bob.zip -d ./appdata/space-engineers-bob/config
fi

sudo docker-compose up -d 
sudo docker-compose logs -f